# Generated by Django 5.2.8 on 2025-11-18 16:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('photo', models.URLField(blank=True, max_length=400, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актор',
                'verbose_name_plural': 'Актори',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('address', models.CharField(max_length=250, verbose_name='Адреса')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Довгота')),
            ],
            options={
                'verbose_name': 'Кінотеатр',
                'verbose_name_plural': 'Кінотеатри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovieBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Новинка, IMAX, Спецпоказ', max_length=100, verbose_name='Текс значка')),
            ],
            options={
                'verbose_name': 'Значок',
                'verbose_name_plural': 'Значки',
            },
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Зала 1', max_length=50, verbose_name='Назва зали')),
                ('number_of_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Кількість місць')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='main.cinemas', verbose_name='Кінотеатр')),
            ],
            options={
                'verbose_name': 'Зала',
                'verbose_name_plural': 'Зали',
                'ordering': ['cinema', 'name'],
                'unique_together': {('cinema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва фільму')),
                ('age_category', models.PositiveSmallIntegerField(choices=[(0, 'Для всіх'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, verbose_name='Вікова категорія')),
                ('description', models.TextField(verbose_name='Опис')),
                ('trailer_url', models.URLField(max_length=400, verbose_name='Трейлер')),
                ('poster_url', models.URLField(max_length=400, verbose_name='Постер')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('release_date', models.DateField(verbose_name='Дата релізу')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата кінця показів')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Тривалість (хвилини)')),
                ('director', models.CharField(max_length=100, verbose_name='Режисер')),
                ('actors', models.ManyToManyField(related_name='movies', to='main.actors', verbose_name='Актори')),
                ('badges', models.ManyToManyField(to='main.moviebadges', verbose_name='Значок/Статус')),
                ('genres', models.ManyToManyField(related_name='movies', to='main.genres', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Номер місця')),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Номер ряду')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='main.halls', verbose_name='Зала')),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
                'ordering': ['hall', 'row', 'num'],
                'unique_together': {('hall', 'row', 'num')},
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата та час')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Ціна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='main.halls', verbose_name='Зала')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='main.movies', verbose_name='Фільм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеанси',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час покупки')),
                ('price', models.IntegerField(help_text='Ціна на момент покупки', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Ціна квитка')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Скасовано')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікується'), ('paid', 'Оплачено'), ('failed', 'Помилка'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус оплати')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='main.seats', verbose_name='Місце')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='main.sessions', verbose_name='Сеанс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
                'ordering': ['-purchase_date_time'],
                'unique_together': {('session', 'seat')},
            },
        ),
    ]
