# Generated by Django 6.0 on 2025-12-10 09:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('photo', models.URLField(blank=True, max_length=1000, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актор',
                'verbose_name_plural': 'Актори',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CinemaBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Parking, IMAX, LUX', max_length=100, verbose_name='Текст значка')),
            ],
            options={
                'verbose_name': 'Значок кінотеатру',
                'verbose_name_plural': 'Значки кінотеатру',
            },
        ),
        migrations.CreateModel(
            name='CityBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovieBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Новинка, IMAX, Спецпоказ', max_length=100, verbose_name='Текст значка')),
                ('description', models.CharField(max_length=225, verbose_name='Опис значка')),
            ],
            options={
                'verbose_name': 'Значок фільму',
                'verbose_name_plural': 'Значки фільму',
            },
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('address', models.CharField(max_length=250, verbose_name='Адреса')),
                ('photo', models.URLField(blank=True, max_length=1000, verbose_name='Фото')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Довгота')),
                ('badges', models.ManyToManyField(to='main.cinemabadges', verbose_name='Значок/Статус кінотеатру')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.citybadges', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Кінотеатр',
                'verbose_name_plural': 'Кінотеатри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Зала 1', max_length=50, verbose_name='Назва зали')),
                ('number_of_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Кількість місць')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='main.cinemas', verbose_name='Кінотеатр')),
            ],
            options={
                'verbose_name': 'Зала',
                'verbose_name_plural': 'Зали',
                'ordering': ['cinema', 'name'],
                'unique_together': {('cinema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва фільму')),
                ('age_category', models.PositiveSmallIntegerField(choices=[(0, 'Для всіх'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, verbose_name='Вікова категорія')),
                ('description', models.TextField(verbose_name='Опис')),
                ('trailer_url', models.URLField(max_length=1000, verbose_name='Трейлер')),
                ('poster_url', models.URLField(max_length=1000, verbose_name='Постер')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('release_date', models.DateField(verbose_name='Дата релізу')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата кінця показів')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Тривалість (хвилини)')),
                ('director', models.CharField(max_length=100, verbose_name='Режисер')),
                ('actors', models.ManyToManyField(related_name='movies', to='main.actors', verbose_name='Актори')),
                ('badges', models.ManyToManyField(to='main.moviebadges', verbose_name='Значок/Статус фільму')),
                ('genres', models.ManyToManyField(related_name='movies', to='main.genres', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час створення')),
                ('total_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Загальна сума')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=15, verbose_name='Статус оплати')),
                ('liqpay_order_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=255, unique=True, verbose_name='ID замовлення (LiqPay)')),
                ('bonuses_earned', models.PositiveIntegerField(default=0, verbose_name='Нараховані бонуси')),
                ('bonuses_used', models.PositiveIntegerField(default=0, verbose_name='Використані бонуси')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кількість бонусів')),
                ('transaction_type', models.CharField(choices=[('accrual', 'Accrual'), ('redemption', 'Redemption'), ('refunded', 'Refunded')], default=[('accrual', 'Accrual'), ('redemption', 'Redemption'), ('refunded', 'Refunded')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses_transactions', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Номер місця')),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Номер ряду')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='main.halls', verbose_name='Зала')),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
                'ordering': ['hall', 'row', 'num'],
                'unique_together': {('hall', 'row', 'num')},
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час початку')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час кінця')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='main.halls', verbose_name='Зала')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.movies', verbose_name='Фільм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеанси',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_balance', models.PositiveIntegerField(default=0, verbose_name='Бонуси')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Ціна на момент покупки', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Ціна квитка')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Скасовано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.order', verbose_name='Замовлення')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='main.seats', verbose_name='Місце')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='main.sessions', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
                'ordering': ['-order__created_at'],
                'unique_together': {('session', 'seat')},
            },
        ),
    ]
