# Generated by Django 5.2.8 on 2025-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='photo',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_url',
            field=models.URLField(max_length=1000, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer_url',
            field=models.URLField(max_length=1000, verbose_name='Трейлер'),
        ),
    ]
