# Generated by Django 5.2.8 on 2025-11-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_actors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster_url',
            field=models.URLField(max_length=400, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer_url',
            field=models.URLField(max_length=400, verbose_name='Трейлер'),
        ),
    ]
